name = "Collatz_julia"
uuid = "a160c32a-55b6-4287-80c9-b6dbff6dde39"
authors = ["Karl Linek <karl@linek.at>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
